// <auto-generated />
using System;
using AutoMarketApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoMarketApp.Infrastructure.Migrations
{
    [DbContext(typeof(AutoMarketAppDbContext))]
    partial class AutoMarketAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoMarketApp.Infrastructure.Data.Dtos.CarDto", b =>
                {
                    b.Property<string>("Vin")
                        .HasColumnType("text");

                    b.HasKey("Vin");

                    b.ToTable("Cars", (string)null);
                });

            modelBuilder.Entity("AutoMarketApp.Infrastructure.Data.Dtos.CustomerDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("AutoMarketApp.Infrastructure.Data.Dtos.CarDto", b =>
                {
                    b.OwnsOne("AutoMarketApp.Infrastructure.Data.Dtos.ReservationDto", "Reservation", b1 =>
                        {
                            b1.Property<string>("CarDtoVin")
                                .HasColumnType("text");

                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid")
                                .HasColumnName("ReservationCustomerId");

                            b1.Property<DateTimeOffset>("ExpirationDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ReservationExpirationDate");

                            b1.Property<DateTimeOffset>("ReservationDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ReservationDate");

                            b1.HasKey("CarDtoVin");

                            b1.HasIndex("CustomerId");

                            b1.ToTable("Cars");

                            b1.WithOwner()
                                .HasForeignKey("CarDtoVin");

                            b1.HasOne("AutoMarketApp.Infrastructure.Data.Dtos.CustomerDto", null)
                                .WithMany()
                                .HasForeignKey("CustomerId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
                        });

                    b.OwnsOne("AutoMarketApp.Infrastructure.Data.Dtos.SaleDto", "Sale", b1 =>
                        {
                            b1.Property<string>("CarDtoVin")
                                .HasColumnType("text");

                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid")
                                .HasColumnName("SaleCustomerId");

                            b1.Property<DateTimeOffset>("SaleDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("SaleDate");

                            b1.HasKey("CarDtoVin");

                            b1.HasIndex("CustomerId");

                            b1.ToTable("Cars");

                            b1.WithOwner()
                                .HasForeignKey("CarDtoVin");

                            b1.HasOne("AutoMarketApp.Infrastructure.Data.Dtos.CustomerDto", null)
                                .WithMany()
                                .HasForeignKey("CustomerId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
                        });

                    b.Navigation("Reservation");

                    b.Navigation("Sale");
                });
#pragma warning restore 612, 618
        }
    }
}
